name: Publish to Figma store

on:
  push:
    branches: [ "production" ]

env:
  FIGMA_WEB_AUTHN_TOKEN: ${{ secrets.FIGMA_WEB_AUTHN_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    
    - name: Enable Corepack and set Yarn version
      run: |
        corepack enable
        corepack prepare yarn@4.9.2 --activate
    
    - name: Install dependencies
      run: | 
        yarn install
      
    - name: Build plugin
      run: |
        yarn build

    - name: Set next Figma version as minor version in package.js
      run: | 
        npx figcd prepare -t ${{ env.FIGMA_WEB_AUTHN_TOKEN }} -m ./dist/manifest.json
          
    - name: Publish new Version to Figma
      run: | 
        npx figcd release -t ${{ env.FIGMA_WEB_AUTHN_TOKEN }} -m ./dist/manifest.json 